EmpresaElectro/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.componentes.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('componentes/', include('apps.componentes.urls')),
    path('fabricantes/', include('apps.fabricantes.urls')),
    path('aparatos/', include('apps.aparatos.urls')),
    path('tipo_ele/', include('apps.tipo_elec.urls')),
]

apps/aparatos/urls.py
from django.urls import path, include

from apps.aparatos.views import aparatoCreate, aparatoEdit, aparatoEliminar, index


app_name = "aparatos"

urlpatterns = [
    path('', index, name='index'),
    path('crear/', aparatoCreate, name='aparatoCreate'),
    path('actualizar/<int:id_aparato>', aparatoEdit, name='aparatoEdit'),
    path('eliminar/<int:id_aparato>', aparatoEliminar, name='aparatoEliminar'),
]

apps/componentes/urls.py
from django.urls import path, include
from apps.componentes.views import componentesEliminar, index, componentesCreate, componentesEdit

app_name = "componentes"

urlpatterns = [
    path('', index, name='index'),
    path('crear/', componentesCreate, name='componentesCreate'),
    path('actualizar/<int:id_componente>', componentesEdit, name='componentesEdit'),
    path('eliminar/<int:id_componente>', componentesEliminar, name='componentesEliminar'),
]

apps/fabricantes/urls.py
from django.urls import path, include
from apps.fabricantes.views import index,fabricanteCreate,fabricanteEdit,fabricanteEliminar


app_name ="fabricantes"
urlpatterns =[
    
    path ('', index,name ='index'),
    path ('nuevo/', fabricanteCreate, name='fabricanteCreate'),
    path ('actualizar/<int:id_fabricante>', fabricanteEdit, name='fabricanteEdit'),
    path ('eliminar/<int:id_fabricante>', fabricanteEliminar, name='fabricanteEliminar')
]


apps/tipo_elec/urls.py
from django.urls import path, include
from apps.tipo_elec.views import TeCreate, TeEdit, TeEliminar, index

app_name = "tipos_ele"

urlpatterns = [
    path('', index, name='index'),
    path('crear/', TeCreate, name='teCreate'),
    path('actualizar/<int:id_te>', TeEdit, name='teEdit'),
    path('eliminar/<int:id_te>', TeEliminar, name='teEliminar'),
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">HOME<i class="fab fa-google-wallet"></i></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      
          <div class="collapse navbar-collapse" id="navbarColor03">
            <ul class="navbar-nav me-auto">
              <!-- <li class="nav-item">
                <a class="nav-link active" href="#">Home
                  <span class="visually-hidden">(current)</span>
                </a>
              </li> -->
              <li class="nav-item">
                <a class="nav-link" href="{% url 'aparatos:index' %}">Aparatos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'componentes:index' %}">Componentes</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'fabricantes:index' %}">Fabricantes</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tipos_ele:index' %}">Tipos de Electrodomesticos</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      {% block content %}

      {% endblock %}

    
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/jquery-3.6.0.min' %}"></script>
      <script src="https://kit.fontawesome.com/11332700d4.js" crossorigin="anonymous"></script>
    </body>
</html>