EmpresaElectro/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.componentes.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('componentes/', include('apps.componentes.urls')),
    path('fabricantes/', include('apps.fabricantes.urls')),
    path('aparatos/', include('apps.aparatos.urls')),
    path('tipo_ele/', include('apps.tipo_elec.urls')),
]

apps/tipo_elec/urls.py
from django.urls import path, include
from apps.tipo_elec.views import TeCreate, TeEdit, TeEliminar, index

app_name = "tipos_ele"

urlpatterns = [
    path('', index, name='index'),
    path('crear/', TeCreate, name='teCreate'),
    path('actualizar/<int:id_te>', TeEdit, name='teEdit'),
    path('eliminar/<int:id_te>', TeEliminar, name='teEliminar'),
]

templates/tipos_ele/formTe.html
{% extends 'base/base.html' %}

{% block content %}

    <h3>Agregar Tipo de electrodomestico</h3>

    <form method="post">


        {% csrf_token %}
        {{ form.as_p }}

        <button class="btn btn-primary" type=submit>
            Guardar
        </button>


    </form>

{% endblock %}

templates/tipos_ele/index.html
{% extends 'base/base.html' %}

{% block content %}
    <h3 style="text-align: center; margin-top: 20px;">Listado de tipos de Electrodomesticos</h3>
    <h1 class="pull-right" style="text-align: center;">
        <a href="{% url 'tipos_ele:teCreate' %}" class="btn btn-primary pull-right">Adicionar</a>
    </h1>

    <table class="table table-bordered table-sm" style="width: 90%; margin: 0 auto;">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Nombre</th>
            <th scope="col">Caracteristicas</th>
            <th scope="col">Aparatos</th>
          </tr>
        </thead>
        <tbody>
        {% for te in tes %}
          <tr>
              <td>{{te.id}}</td>
              <td>{{te.nombre}}</td>
              <td>{{te.caracteristicas}}</td>
              <td>{{te.aparatos.descripcion}}</td>
              <td>
                <a class="btn btn-warning btn-xs" href="{% url 'tipos_ele:teEdit' te.id %}">
                    <i class="fas fa-edit"></i>
                </a>
                <a class="btn btn-danger btn-xs" href="{% url 'tipos_ele:teEliminar' te.id %}">
                    <i class="fas fa-trash"></i>
                </a>
              </td>
        {% endfor %}
          </tr>
          
        </tbody>
      </table>
{% endblock %}

templates/tipos_ele/teEliminar.html
{% extends 'base/base.html' %}

{% block content %}

    <form method="post">


        {% csrf_token %}
        {{ form.as_p }}
        <h4>¿Desea eliminar el registro de {{ te.nombre }} ?</h4>
        <button class="btn btn-danger" type=submit>
            Sí, eliminar
        </button>
        <a class="btn btn-primary" href="{% url 'tipos_ele:index' %}">Cancelar</a>


    </form>

{% endblock %}