EmpresaElectro/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.componentes.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('componentes/', include('apps.componentes.urls')),
    path('fabricantes/', include('apps.fabricantes.urls')),
    path('aparatos/', include('apps.aparatos.urls')),
    path('tipo_ele/', include('apps.tipo_elec.urls')),
]

apps/aparatos/urls.py
from django.urls import path, include

from apps.aparatos.views import aparatoCreate, aparatoEdit, aparatoEliminar, index


app_name = "aparatos"

urlpatterns = [
    path('', index, name='index'),
    path('crear/', aparatoCreate, name='aparatoCreate'),
    path('actualizar/<int:id_aparato>', aparatoEdit, name='aparatoEdit'),
    path('eliminar/<int:id_aparato>', aparatoEliminar, name='aparatoEliminar'),
]

apps/aparatos/models.py
from django.db import models

class Aparatos(models.Model):
    descripcion = models.CharField(max_length=300)

    def __str__(self):
        return self.descripcion

apps/aparatos/views.py
from django.shortcuts import redirect, render
from apps.aparatos.models import Aparatos
from apps.aparatos.form import AparatoForm

# Create your views here.

def index(request):
    aparato = Aparatos.objects.all()
    context = {'aparatos': aparato}
    return render (request,'aparatos/index.html',context)

def aparatoCreate(request):
    if(request.method == 'POST'):
        form = AparatoForm(request.POST)
        if form.is_valid():
            form.save()

        return redirect('aparatos:index')
    else:
        form = AparatoForm()
        return render(request, 'aparatos/formAparato.html', {'form': form})


def aparatoEdit(request, id_aparato):

    aparato = Aparatos.objects.get(pk=id_aparato)
    if(request.method == 'GET'):
        form = AparatoForm(instance=aparato)
    else:
        form = AparatoForm(request.POST, instance=aparato)
        if form.is_valid():
            form.save()

        return redirect('aparatos:index')

    return render(request, 'aparatos/formAparato.html', {'form': form})


def aparatoEliminar(request, id_aparato):

    aparato = Aparatos.objects.get(pk=id_aparato)

    if(request.method == 'POST'):
        aparato.delete()
        return redirect('aparatos:index')

    return render(request, 'aparatos/aparatoEliminar.html', {'aparato': aparato})

templates/aparatos/aparatoEliminar.html
{% extends 'base/base.html' %}

{% block content %}

    <form method="post">


        {% csrf_token %}
        {{ form.as_p }}
        <h4>¿Desea eliminar el registro de {{ aparato.descripcion }} ?</h4>
        <button class="btn btn-danger" type=submit>
            Sí, eliminar
        </button>
        <a class="btn btn-primary" href="{% url 'aparatos:index' %}">Cancelar</a>


    </form>

{% endblock %}

templates/aparatos/formAparato.html
{% extends 'base/base.html' %}

{% block content %}

    <h3>Agregar componente</h3>

    <form method="post">


        {% csrf_token %}
        {{ form.as_p }}

        <button class="btn btn-primary" type=submit>
            Guardar
        </button>


    </form>

{% endblock %}

templates/aparatos/index.html
{% extends 'base/base.html' %}

{% block content %}
    <h3 style="text-align: center; margin-top: 20px;">Listado de Aparatos</h3>
    <h1 class="pull-right" style="text-align: center;">
        <a href="{% url 'aparatos:aparatoCreate' %}" class="btn btn-primary pull-right">Adicionar</a>
    </h1>

    <table class="table table-bordered table-sm" style="width: 90%; margin: 0 auto;">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Descripcion</th>
          </tr>
        </thead>
        <tbody>
        {% for aparato in aparatos %}
          <tr>
              <td>{{aparato.id}}</td>
              <td>{{aparato.descripcion}}</td>
              <td>
                <a class="btn btn-warning btn-xs" href="{% url 'aparatos:aparatoEdit' aparato.id %}">
                    <i class="fas fa-edit"></i>
                </a>
                <a class="btn btn-danger btn-xs" href="{% url 'aparatos:aparatoEliminar' aparato.id %}">
                    <i class="fas fa-trash"></i>
                </a>
              </td>
        {% endfor %}
          </tr>
          
        </tbody>
      </table>
{% endblock %}