EmpresaElectro/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.componentes.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('componentes/', include('apps.componentes.urls')),
    path('fabricantes/', include('apps.fabricantes.urls')),
    path('aparatos/', include('apps.aparatos.urls')),
    path('tipo_ele/', include('apps.tipo_elec.urls')),
]

apps/fabricantes/urls.py
from django.urls import path, include
from apps.fabricantes.views import index,fabricanteCreate,fabricanteEdit,fabricanteEliminar


app_name ="fabricantes"
urlpatterns =[
    
    path ('', index,name ='index'),
    path ('nuevo/', fabricanteCreate, name='fabricanteCreate'),
    path ('actualizar/<int:id_fabricante>', fabricanteEdit, name='fabricanteEdit'),
    path ('eliminar/<int:id_fabricante>', fabricanteEliminar, name='fabricanteEliminar')
]


apps/fabricantes/models.py
from django.db import models


# Create your models here.

class Fabricantes(models.Model):
    nombre = models.CharField(max_length=60)
    domicilio = models.CharField(max_length=200)
    componentes = models.CharField(max_length=200)

    def __str__(self):
        return self.nombre

apps/fabricantes/views.py
from django.shortcuts import render,redirect

from apps.fabricantes.form import fabricanteForm
from apps.fabricantes.models import Fabricantes

# Create your views here.  
def index (request):
    fabricantes = Fabricantes.objects.all().order_by('id')
    context ={'fabricantes': fabricantes}
    return render (request,'fabricantes/index.html',context)
    # return render(request,'fabricantes/index.html')

def fabricanteCreate(request):
        if (request.method =='POST'):
            form =fabricanteForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('fabricantes:index')
        else:
            form =fabricanteForm()
            return render(request,'fabricantes/formFabricante.html',{'form': form})

def fabricanteEdit(request, id_fabricante):
    fabricante= Fabricantes.objects.get(pk=id_fabricante)
    if (request.method =='GET'):
        form =fabricanteForm(instance= fabricante)
    else:
        form =fabricanteForm(request.POST,instance=fabricante)
        if  form.is_valid():
            form.save()
        return redirect ('fabricantes:index')
    return render(request,'fabricantes/formFabricante.html',{'form':form})

def fabricanteEliminar (request, id_fabricante):
    fabricante= Fabricantes.objects.get(pk=id_fabricante)
    if request.method =='POST':
        fabricante.delete()
        return redirect ('fabricantes:index')
    return render(request, 'fabricantes/fabricanteEliminar.html',{'fabricante':fabricante})

templates/fabricantes/fabricanteEliminar.html
{% extends 'base/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <h4> DESEA ELIMINAR EL Fabricante DE {{ fabricantes.nombre}} ?</h4>
        <button class="btn btn-danger" type="submit">SI, Eliminar</button>
        <a class="btn btn-primary" href="{% url 'fabricantes:index' %}">Cancelar</a>

    </form>
{% endblock %}

templates/fabricantes/formFabricante.html
{% extends 'base/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button class="btn btn-primary" type="submit">
            Guardar
        </button>
    </form>
{% endblock %}

templates/fabricantes/index.html
{% extends 'base/base.html' %}

{% block content %}
    <h3>Listado de fabricantes</h3>
    <a href="{% url 'fabricantes:fabricanteCreate' %}" 
      class="btn btn-primary pull-right">Agregar</a>
    </h1>
    <table class="table table-dark table-striped">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Nombre</th>
            <th scope="col">Domicilio</th>
            <th scope="col">Componentes</th>
          </tr>
        </thead>
        <tbody>
          {% if fabricantes %}
          {% for fabricante in fabricantes %}
          <tr>
            
              <td>{{fabricante.id}}</td>
              <td>{{fabricante.nombre}}</td>
              <td>{{fabricante.domicilio}}</td>
              <td>{{fabricante.componentes}}</td>
              <td>
                <a class="btn btn-warning " href="{% url 'fabricantes:fabricanteEdit' fabricante.id %}" >
                  ACTUALIZAR</a>
                <a class="btn btn-danger" href="{% url 'fabricantes:fabricanteEliminar' fabricante.id %}">
                  ELIMINAR</a>
              </td>
          </tr>
          {% endfor %}
          {% else %}
          <h3>NO EXISTEN REGISTROS DE FABRICANTES</h3>
        {% endif %}
        </tbody>
      </table>
{% endblock %}

templates/fabricantes/inicio.html
{% extends 'base/base.html' %}

{% block content %}
    <h3>MOSTRANDO AL FIN ...</h3>
{% endblock %}